#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2025, Jeremy Goossen jgoossen851@proton.me

# General Purpose Macro Processor
#
# Caution: This script has almost no error detection or safeguards.
#          Use at your own risk.

IN_FILE="${1:-/dev/stdin}"
OUT_FILE="${2:-/dev/stdout}"

TMP_FILE="$(mktemp)"

DEBUG=0

# Start, or continue, printing output verbatim from input
function verbatim_mode () {
if [ ${VERBATIM_MODE} -eq 0 ]; then
  echo "cat << EOF" >> "${TMP_FILE}"
  VERBATIM_MODE=1
fi
}

# Start, or continue, running commands to affect how output is produced
function command_mode () {
if [ ${VERBATIM_MODE} -eq 1 ]; then
  echo "EOF" >> "${TMP_FILE}"
  VERBATIM_MODE=0
fi
}

function parse_directives () {
# Parse directives from input $1 to output script $2
  VERBATIM_MODE=0
  while IFS= read -r line; do
    case "${line}" in
      "#shell "*) command_mode # Run line verbatim in shell
        echo "${line#"#shell "}" >> "${2}"
      ;;
      "#include "*) command_mode # Parse the given file to the shell as a script
        # Any variables used in the included files should have been previously defined
        parse_directives "${line#"#include "}" "${2}"
      ;;
      "#call "*) command_mode # Parse the given file to the shell as a function
        # The remainder of the line is parsed as the contents of the array ARGS
        read -r -a CONTENTS <<<"${line#"#call "}"
        ARGS=("${CONTENTS[@]:1}") # Contents without the first element
        declare -p ARGS >> "${2}" # Define ARGS in the generated script
        parse_directives "${CONTENTS[0]}" "${2}"
      ;;
      "#calc "*) command_mode  # Floating point calculation, using awk
        # The expression is formatted with a printf format-spec and saved to an output variable, called as
        #calc  %fmt  OUTPUT_VAR  $EXPRESSION + $TO + $EVALUATE
        FMT_SPEC='%.*?[diuoxXfFeEgGaAcspn%]'
        OUT_VAR='[A-Za-z][A-Za-z0-9_]*'
        EXPRESSION='.*'
        IN_REGEX="^#calc\s+(${FMT_SPEC})\s+(${OUT_VAR})\s+(${EXPRESSION})$"
        # shellcheck disable=SC2016
        OUT_REGEX='\2="$(awk "BEGIN {printf \\"\1\\", \3 }")"'
        sed -E "s/${IN_REGEX}/${OUT_REGEX}/" <<<"${line}" >> "${2}"
      ;;
      *) verbatim_mode # Copy input to output, only replacing variables
        echo "${line}" >> "${2}"
      ;;
    esac
  done < "${1}"
  command_mode
}

# Read the input file line-by-line, and generate a script to write the output file
echo "#!/bin/bash" >> "${TMP_FILE}"
echo >> "${TMP_FILE}"
echo "echo \"# This file was autogenerated from ${IN_FILE} using ${0}\"" >> "${TMP_FILE}"
echo "echo" >> "${TMP_FILE}"
# File body
parse_directives "${IN_FILE}" "${TMP_FILE}"

# Debug output: View generated file
if [ ${DEBUG} -gt 0 ]; then
  1>&2 echo -en "\e[2m"
  1>&2 cat "${TMP_FILE}"
  1>&2 echo -en "\e[0m"
fi

# Use the generated file to produce the processed output
bash "${TMP_FILE}" > "${OUT_FILE}"
rm "${TMP_FILE}"
